### ISSUE TITLE
.bin/bkndredux throws a syntax error on Windows

### ISSUE THREAD

**Issue by cytrowski** [backand/redux-sdk#2]
When we generate Types, Actions, and Reducers on Windows using:
```
node "./node_modules/.bin/bkndredux" user
```
 this is the outcome:

```node "./node_modules/.bin/bkndredux" user
C:\Users\...\node_modules\.bin\bkndredux:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

```
node -v
v6.10.0
```

Windows 10, 64bit

**Comment by ghost** [comment]
Confirming above, same issue here. Need to call "node_modules\.bin\bkndredux.cmd" directly.
